# Generated by Django 2.2.4 on 2021-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210409_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain_text',
            field=models.TextField(max_length=255, verbose_name='Текст жалобы'),
        ),
    ]
