# Generated by Django 2.2.4 on 2021-04-09 16:22

from django.db import migrations
import phonenumbers


def add_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(phone):
            flat.owner_pure_phone = phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()
        else:
            flat.owner_pure_phone = 'Невалидный номер телефона'
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20210409_1904'),
    ]

    operations = [
        migrations.RunPython(add_pure_phone)

    ]
