# Generated by Django 2.2.4 on 2021-04-09 18:00

from django.db import migrations
import os


def transfer_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber,
            pure_phone_number=flat.owner_pure_phone,
        )
        owner[0].owned_flats.set([flat])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20210409_2030'),
    ]

    operations = [
        migrations.RunPython(transfer_flats_to_owners)

    ]
